#!/usr/bin/php
<?php
/**
 * Deploy
 * 
 * Deployment automation framework
 * 
 * @author Leonid Mamchenkov <l.mamchenkov@qobo.biz>
 */
namespace Deploy\App;

// Load libraries
require_once 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php';
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'lib' . DIRECTORY_SEPARATOR . 'Deploy' . DIRECTORY_SEPARATOR . 'autoload.php';

// Run the app
try {
	$app = new App($argv);
	$app->run();
}
// Missing parameters show the help message and error
catch (\Deploy\Exception\MissingParameterException $e) {
	print "ERROR: " . $e->getMessage();
	print App::help();
	die(1);

}
// Everything else just shows the error
catch (\Exception $e) {
	print "ERROR: " . $e->getMessage();
	die(1);
}

?>
